### PR TITLE
fetch repos via https

### PR DESCRIPTION
**Pull request by christian-rauch**
Fix loading from YAML, based on https://github.com/ethz-asl/aerial_mapper/issues/45#issuecomment-601986334

I set the repo URLs to https so they can be fetched without having to add an ssh key.

### CODE REVIEW

**Review by HannesSommer — APPROVED** [review]
Thanks!

**Comment by HannesSommer** [comment]
ok to test

**Comment by HannesSommer** [comment]
@christian-rauch ,  currently CI is failing. Because of a missing dep. Once #100  is merged (containing already your YAML fix in order for it to build), you should be able to interactively rebase on the new master (dropping the YAML fix to avoid conflicts). Then we can merge this MR too.

**Comment by christian-rauch** [comment]
I couldn't check the CI because it requires access to private repos ("This application will be able to read your organization, team membership, and private project boards."), which I am not really happy to provide.

Is it possible to see the CI output somewhere publicly?

**Comment by christian-rauch** [comment]
I rebased so that only one commit for the https change is left and renamed this PR accordingly

**Comment by HannesSommer** [comment]
Unfortunately this is currently not possible. The CI problem was probably the one I anticipated in my last message. The #100 was merged much later. I integrated the change now. And it solved it. Merging.

**Pull request merged**
